server {
    listen 80;
    server_name localhost;

    client_max_body_size 100M;

    # 静态网页托管 (支持 SPA 路由刷新)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 后端 API 反向代理
    location /api/ {
        proxy_pass http://cybermind-backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_request_buffering off;  # 禁用请求缓冲，适用于大文件上传
    }

    # 本地文件存储反向代理
    location /uploads/ {
        proxy_pass http://cybermind-backend:8000/uploads/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        client_max_body_size 100M;  # 设置上传文件大小限制
        proxy_read_timeout 3600s;  # 设置读取超时时间，适用于大文件上传
        proxy_connect_timeout 3600s;  # 设置连接超时时间，适用于大文件上传
        proxy_send_timeout 3600s;  # 设置发送超时时间，适用于大文件上传
        proxy_request_buffering off;  # 禁用请求缓冲，适用于大文件上传
    }

    # 错误页面
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
