"""add_news_table

Revision ID: 07cb46f3885a
Revises: 541c5248b0f9
Create Date: 2026-06-07 01:12:20.088357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '07cb46f3885a'
down_revision: Union[str, Sequence[str], None] = '541c5248b0f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('cover_image', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('is_top', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_articles')
    # ### end Alembic commands ###
