"""add_site_config_table

Revision ID: 541c5248b0f9
Revises: c01c47264e2e
Create Date: 2026-06-07 01:09:06.878520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '541c5248b0f9'
down_revision: Union[str, Sequence[str], None] = 'c01c47264e2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('config_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_configs_config_key'), 'site_configs', ['config_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_configs_config_key'), table_name='site_configs')
    op.drop_table('site_configs')
    # ### end Alembic commands ###
