"""add_tracking_event_table

Revision ID: db0b2e9743b7
Revises: 8081d2d076c7
Create Date: 2026-06-07 01:46:31.900095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'db0b2e9743b7'
down_revision: Union[str, Sequence[str], None] = '8081d2d076c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('page_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_events_fingerprint'), 'tracking_events', ['fingerprint'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracking_events_fingerprint'), table_name='tracking_events')
    op.drop_table('tracking_events')
    # ### end Alembic commands ###
